new diagram and code examples to explain volatile and atomicic operat…
learn-co-curriculum/java-mod-5-shared-data-part-1 pull request #2
Opened 2022-10-19 13:45 UTC by linda-seiter

…ions

2022-10-19 16:40 UTC, kcleland0818 requested changes

2022-10-19 16:40 UTC, kcleland0818 commented on README.md
> +If we run the program it will most likely print `a + b = 12` or `a = 0 b = 0`, but it
Isn't it `a + b = 7` not `a + b = 12`?

2022-10-19 18:24 UTC, linda-seiter commented on README.md
> +If we run the program it will most likely print `a + b = 12` or `a = 0 b = 0`, but it
good catch, thanks!

2022-10-19 18:30 UTC, kcleland0818 approved these changes

2022-10-25 15:46 UTC, AlveeM approved these changes

2022-10-25 15:46 UTC, merged